パス変更

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Fail fast and fail hard.
+set -eo pipefail
+
 # ユーティリティ タイトル表示
 title() {
     echo "-----> $*"
@@ -28,7 +31,7 @@ CACHE_DIR=$2 #/app/tmp/cache
 title "build step by step"
 
 # mecab buildpack
-source BIN_DIR/steps/compile-mecab BUILD_DIR INSTALL_DIR CACHE_DIR
+source $BIN_DIR/steps/compile-mecab $BUILD_DIR $INSTALL_DIR $CACHE_DIR
 
 # ビルド結果の保存
 (cd $HOME && tar cf - .vendor) | (cd $BUILD_DIR && tar xf -)
